/** @type {import('tailwindcss').Config['theme']} */
export const sharedTheme = {
  extend: {
    colors: {
      background: 'hsl(var(--background))',
      foreground: 'hsl(var(--foreground))',
      card: 'hsl(var(--card))',
      'card-foreground': 'hsl(var(--card-foreground))',
      popover: 'hsl(var(--popover))',
      'popover-foreground': 'hsl(var(--popover-foreground))',
      primary: 'hsl(var(--primary))',
      'primary-foreground': 'hsl(var(--primary-foreground))',
      secondary: 'hsl(var(--secondary))',
      'secondary-foreground': 'hsl(var(--secondary-foreground))',
      muted: 'hsl(var(--muted))',
      'muted-foreground': 'hsl(var(--muted-foreground))',
      accent: 'hsl(var(--accent))',
      'accent-foreground': 'hsl(var(--accent-foreground))',
      destructive: 'hsl(var(--destructive))',
      'destructive-foreground': 'hsl(var(--destructive-foreground))',
      border: 'hsl(var(--border))',
      input: 'hsl(var(--input))',
      ring: 'hsl(var(--ring))',
      success: 'hsl(var(--success))',
      'success-foreground': 'hsl(var(--success-foreground))',
      warning: 'hsl(var(--warning))',
      'warning-foreground': 'hsl(var(--warning-foreground))',
      info: 'hsl(var(--info))',
      'info-foreground': 'hsl(var(--info-foreground))',
      'diff-add': 'hsl(var(--diff-add))',
      'diff-add-foreground': 'hsl(var(--diff-add-foreground))',
      'diff-remove': 'hsl(var(--diff-remove))',
      'diff-remove-foreground': 'hsl(var(--diff-remove-foreground))',
      'diff-modify': 'hsl(var(--diff-modify))',
      'diff-modify-foreground': 'hsl(var(--diff-modify-foreground))',
    },
    borderRadius: {
      DEFAULT: 'var(--radius)',
    },
  },
};
